### ISSUE TITLE
LC-349 time complexity

### ISSUE THREAD

**Issue by bigjiji0204** [yungshenglu/LeetCode#1]
Can be done in O(n) through hash set

**Comment by yungshenglu** [comment]
Thanks for your great issue. Do you mean just to find out the shortest list without sorting before?

**Comment by yungshenglu** [comment]
@bigjiji0204 
I have already finished another approach using the hash table to make it done in O(n). Thanks for your issue and here is the [source code](https://github.com/yungshenglu/LeetCode/blob/master/LC-349/LC-349-2.cpp).
